
package io.renren.modules.account.webclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UploadBankData", targetNamespace = "http://testWebservice.pxCreditrating.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UploadBankData {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValue", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.GetValue")
    @ResponseWrapper(localName = "getValueResponse", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.GetValueResponse")
    @Action(input = "http://testWebservice.pxCreditrating.com/UploadBankData/getValueRequest", output = "http://testWebservice.pxCreditrating.com/UploadBankData/getValueResponse")
    public String getValue(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param password
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadSpecialAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UploadSpecialAccount", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.UploadSpecialAccount")
    @ResponseWrapper(localName = "UploadSpecialAccountResponse", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.UploadSpecialAccountResponse")
    @Action(input = "http://testWebservice.pxCreditrating.com/UploadBankData/UploadSpecialAccountRequest", output = "http://testWebservice.pxCreditrating.com/UploadBankData/UploadSpecialAccountResponse")
    public String uploadSpecialAccount(
        @WebParam(name = "xmlData", targetNamespace = "")
        String xmlData,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadSettlement")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UploadSettlement", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.UploadSettlement")
    @ResponseWrapper(localName = "UploadSettlementResponse", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.UploadSettlementResponse")
    @Action(input = "http://testWebservice.pxCreditrating.com/UploadBankData/UploadSettlementRequest", output = "http://testWebservice.pxCreditrating.com/UploadBankData/UploadSettlementResponse")
    public String uploadSettlement(
        @WebParam(name = "xmlData", targetNamespace = "")
        String xmlData,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param prjHtbaNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FindBankAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindBankAccount", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.FindBankAccount")
    @ResponseWrapper(localName = "FindBankAccountResponse", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.FindBankAccountResponse")
    @Action(input = "http://testWebservice.pxCreditrating.com/UploadBankData/FindBankAccountRequest", output = "http://testWebservice.pxCreditrating.com/UploadBankData/FindBankAccountResponse")
    public String findBankAccount(
        @WebParam(name = "prjHtbaNum", targetNamespace = "")
        String prjHtbaNum,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadBankAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UploadBankAccount", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.UploadBankAccount")
    @ResponseWrapper(localName = "UploadBankAccountResponse", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.UploadBankAccountResponse")
    @Action(input = "http://testWebservice.pxCreditrating.com/UploadBankData/UploadBankAccountRequest", output = "http://testWebservice.pxCreditrating.com/UploadBankData/UploadBankAccountResponse")
    public String uploadBankAccount(
        @WebParam(name = "xmlData", targetNamespace = "")
        String xmlData,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param xmlData
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UploadPersonBankAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UploadPersonBankAccount", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.UploadPersonBankAccount")
    @ResponseWrapper(localName = "UploadPersonBankAccountResponse", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.UploadPersonBankAccountResponse")
    @Action(input = "http://testWebservice.pxCreditrating.com/UploadBankData/UploadPersonBankAccountRequest", output = "http://testWebservice.pxCreditrating.com/UploadBankData/UploadPersonBankAccountResponse")
    public String uploadPersonBankAccount(
        @WebParam(name = "xmlData", targetNamespace = "")
        String xmlData,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param zjhm
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "FindPersonBankAccount")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindPersonBankAccount", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.FindPersonBankAccount")
    @ResponseWrapper(localName = "FindPersonBankAccountResponse", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.FindPersonBankAccountResponse")
    @Action(input = "http://testWebservice.pxCreditrating.com/UploadBankData/FindPersonBankAccountRequest", output = "http://testWebservice.pxCreditrating.com/UploadBankData/FindPersonBankAccountResponse")
    public String findPersonBankAccount(
        @WebParam(name = "zjhm", targetNamespace = "")
        String zjhm,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param zjhm
     * @param prjHtbaNum
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "IsPersonInProject")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "IsPersonInProject", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.IsPersonInProject")
    @ResponseWrapper(localName = "IsPersonInProjectResponse", targetNamespace = "http://testWebservice.pxCreditrating.com/", className = "io.renren.modules.account.webclient.IsPersonInProjectResponse")
    @Action(input = "http://testWebservice.pxCreditrating.com/UploadBankData/IsPersonInProjectRequest", output = "http://testWebservice.pxCreditrating.com/UploadBankData/IsPersonInProjectResponse")
    public String isPersonInProject(
        @WebParam(name = "prjHtbaNum", targetNamespace = "")
        String prjHtbaNum,
        @WebParam(name = "zjhm", targetNamespace = "")
        String zjhm,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
