
package io.renren.modules.account.webclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UploadBankDataService", targetNamespace = "http://testWebservice.pxCreditrating.com/", wsdlLocation = "http://121.41.32.132:8980/payDataService/uploadBankData?wsdl")
public class UploadBankDataService
    extends Service
{

    private final static URL UPLOADBANKDATASERVICE_WSDL_LOCATION;
    private final static WebServiceException UPLOADBANKDATASERVICE_EXCEPTION;
    private final static QName UPLOADBANKDATASERVICE_QNAME = new QName("http://testWebservice.pxCreditrating.com/", "UploadBankDataService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://121.41.32.132:8980/payDataService/uploadBankData?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPLOADBANKDATASERVICE_WSDL_LOCATION = url;
        UPLOADBANKDATASERVICE_EXCEPTION = e;
    }

    public UploadBankDataService() {
        super(__getWsdlLocation(), UPLOADBANKDATASERVICE_QNAME);
    }

    public UploadBankDataService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPLOADBANKDATASERVICE_QNAME, features);
    }

    public UploadBankDataService(URL wsdlLocation) {
        super(wsdlLocation, UPLOADBANKDATASERVICE_QNAME);
    }

    public UploadBankDataService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPLOADBANKDATASERVICE_QNAME, features);
    }

    public UploadBankDataService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UploadBankDataService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UploadBankData
     */
    @WebEndpoint(name = "UploadBankDataPort")
    public UploadBankData getUploadBankDataPort() {
        return super.getPort(new QName("http://testWebservice.pxCreditrating.com/", "UploadBankDataPort"), UploadBankData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UploadBankData
     */
    @WebEndpoint(name = "UploadBankDataPort")
    public UploadBankData getUploadBankDataPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://testWebservice.pxCreditrating.com/", "UploadBankDataPort"), UploadBankData.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UPLOADBANKDATASERVICE_EXCEPTION!= null) {
            throw UPLOADBANKDATASERVICE_EXCEPTION;
        }
        return UPLOADBANKDATASERVICE_WSDL_LOCATION;
    }

}
